# Generated by Django 2.1.2 on 2018-10-29 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=200)),
                ('price', models.FloatField(default=0)),
            ],
        ),
        migrations.RenameModel(
            old_name='admins',
            new_name='admin',
        ),
        migrations.RenameModel(
            old_name='customers',
            new_name='customer',
        ),
        migrations.RenameModel(
            old_name='delivery_addresses',
            new_name='delivery_address',
        ),
        migrations.RenameModel(
            old_name='logins',
            new_name='login',
        ),
        migrations.RenameModel(
            old_name='orders',
            new_name='order',
        ),
        migrations.RemoveField(
            model_name='products',
            name='cat_id',
        ),
        migrations.AlterField(
            model_name='order_item',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
        migrations.RenameModel(
            old_name='categories',
            new_name='category',
        ),
        migrations.RenameModel(
            old_name='order_items',
            new_name='order_item',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.AddField(
            model_name='product',
            name='cat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category'),
        ),
    ]
